apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: demo
  labels: {app: web}
spec:
  replicas: 2
  selector:
    matchLabels: {app: web}
  template:
    metadata:
      labels: {app: web}
    spec:
      containers:
      - name: nginx
        image: nginxinc/nginx-unprivileged:1.28-alpine
        ports:
        - {name: http, containerPort: 8080}
        volumeMounts:
        - {name: conf, mountPath: /etc/nginx/conf.d}
        readinessProbe:
          httpGet: {path: /, port: http}
        livenessProbe:
          httpGet: {path: /, port: http}
          initialDelaySeconds: 10
        resources:
          requests: {cpu: 20m, memory: 32Mi}
          limits: {cpu: 200m, memory: 128Mi}
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          capabilities: {drop: [ALL]}
      volumes:
      - name: conf
        configMap: {name: web-nginx}
