apiVersion: v1
kind: ConfigMap
metadata:
  name: web-v2-nginx
  namespace: demo
data:
  default.conf: |
    server {
      listen 8080;
      location / {
        default_type text/plain;
        return 200 "Hello World! v2\n";
      }
      location /stub_status {
        stub_status;
        access_log off;
      }
    }
